



```
#Import random
randomlist = []
for i in range(0,5):
    n = random.randint(1,30)
    randomlist.append(n)
print(randomlist)
```

Esse comando gera numeros aleatórios:
import random (resumindo permite o uso do comando)
for i in range(0,5) (esse for é para gerar 5 números aleatório)
n = random.randint(1,30) (esse comando é para gerar números aleatórios entre 1 e 30)
print(randomlist) (impressão dos números aleatórios



In [ ]:
import random 
import numpy as np


In [ ]:
#NÚMERO ALEATÓRIO ENTRE 0 E 1
y = random.random() 
print(y)

0.6417216990189537


In [ ]:
x = []
x.append(random.random())
print(x)

[0.6323381197214418]


In [ ]:
x = []
for i in range(10):
  x.append(random.random())
print(x)

0
1
2
3
4
5
6
7
8
9


In [ ]:
#10 NÚMEROS ALEATÓRIOS
y = [random.random() for n in range(10)]
print(y)


[0.7116541515550118, 0.09858871225799504, 0.9049237580290922, 0.43784971219707747, 0.9118113961978246, 0.7622542694475682, 0.8441452804097378, 0.4035334311837768, 0.05586600661425667, 0.3541278436046652]


In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
n = 10
z = list(range(0,n))
print(z)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
random.choice(a)


4

In [ ]:
np.random.rand(10,3,4,5).ravel()[0]


In [ ]:
n = 10
a = range(5)
x = [random.choice(a) for n in range (n)] #gerou uma lista com base na quantidade de vezes (range) estabelecido na variável 'n' de forma aleatorizada com elementos de 'a' (random.choice)
y = [random.random() for n in range(n)]
z = list(range(n)) #uma lista de valores de 0 a N, aleatorizada. Não sabe em que sequência está apresentada esses números;
random.shuffle(z) #The "shuffle()" embaralha os elemnetos de uma função 
A=np.random.rand(n,3) #matriz de N filas com 3 colunas; 

print(len(x))
print(x)
print(y)
print('z',z)
print(A)
print('Done')

10
[1, 4, 4, 4, 3, 0, 3, 2, 2, 2]
[0.3617214631937187, 0.39887637672841403, 0.6236619049031146, 0.09581048205449805, 0.8010913911916685, 0.5371814702943064, 0.12853961739834674, 0.2704114161261473, 0.3904069897735276, 0.6232286412348967]
z [3, 9, 2, 5, 6, 0, 7, 1, 4, 8]
[[0.04247146 0.2342727  0.56374729]
 [0.98876753 0.91339864 0.99295862]
 [0.54802012 0.62864508 0.86950966]
 [0.68519991 0.33722971 0.64487999]
 [0.40781126 0.77817221 0.77936105]
 [0.703309   0.78660978 0.87616182]
 [0.14736014 0.40538282 0.98032297]
 [0.54367627 0.34776133 0.96394112]
 [0.18921452 0.54339911 0.89193528]
 [0.14584991 0.807068   0.76190674]]
Done


In [ ]:
x = [1, 2, 3, 4, 5]

min = x[0]
for n in range(len(x)):
  if min > x[n]:
     min = x[n]  
max = x[0]
for n in range(len(x)):
  if max < x[n]:
    max = x[n]


In [ ]:
x = (x + 1)
x_sum = x_sum + x[n]
x_media = x_sum/x 


In [ ]:
N = 10
S = 0;
x_sum = 0;
for i in range(N):
  S = S + 1 #counter
  x_sum=x_sum+x[1]
  #print(S)
  #print(x_sum)
mean_value=x_sum/S
print(mean_value)

2.0


In [ ]:
min = mean[2]
for n in range(len(mean_value)):
  if min > mean_value[n]:
    min = mean_value[n]
#refazer - não entendi; 

In [ ]:
import random   #continuar... 
n = 100
x = list(range(0, n))
print(x)

ordem=1


for i in range(1+l, N):
  #sorting values inascendent order
  if (ordem == 1) & (x[j]>value_ref):  
